version: "3.9"

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hpi
      POSTGRES_USER: hpi
      POSTGRES_PASSWORD: hpi
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
